rootProject.name = "kotlin-extensions"

include(":argparse")
include(":extensions")
include(":identifier")
include(":serialization")
include(":concurrent")
include(":json")
include(":scripts")
include(":logging")
include(":krest")
include(":javalin")
include(":jline")
include(":math")
include(":wsrpc")
include(":mongo")
include(":kafka")
include(":spark")
include(":utils")
include(":uuid")
include(":tree")
include(":swarm")
include(":unittest")
include(":iobuffer")
include(":unsigned")
