@file:Suppress("unused")

package ru.inforion.lab403.common.extensions

inline val Long.long: Long get() = toLong()
inline val Long.int: Int get() = toInt()
inline val Long.short: Short get() = toShort()
inline val Long.byte: Byte get() = toByte()
inline val Long.float: Float get() = toFloat()
inline val Long.double: Double get() = toDouble()
inline val Long.char: Char get() = Char(ushort)

inline val Int.long: Long get() = toLong()
inline val Int.asULong: Long get() = toULong()
inline val Int.int: Int get() = toInt()
inline val Int.short: Short get() = toShort()
inline val Int.byte: Byte get() = toByte()
inline val Int.float: Float get() = toFloat()
inline val Int.double: Double get() = toDouble()
inline val Int.char: Char get() = toChar()

inline val Short.long: Long get() = toLong()
inline val Short.asULong: Long get() = toULong()
inline val Short.asUInt: Int get() = toUInt()
inline val Short.int: Int get() = toInt()
inline val Short.short: Short get() = toShort()
inline val Short.byte: Byte get() = toByte()
inline val Short.float: Float get() = toFloat()
inline val Short.double: Double get() = toDouble()
inline val Short.char: Char get() = Char(ushort)

inline val Byte.long: Long get() = toLong()
inline val Byte.asULong: Long get() = toULong()
inline val Byte.asUInt: Int get() = toUInt()
inline val Byte.int: Int get() = toInt()
inline val Byte.short: Short get() = toShort()
inline val Byte.byte: Byte get() = toByte()
inline val Byte.float: Float get() = toFloat()
inline val Byte.double: Double get() = toDouble()
inline val Byte.char: Char get() = Char(ushort)

inline val Char.long: Long get() = code.toLong()
inline val Char.asULong: Long get() = toULong()
inline val Char.asUInt: Int get() = toUInt()
inline val Char.int: Int get() = code
inline val Char.short: Short get() = code.toShort()
inline val Char.byte: Byte get() = code.toByte()
inline val Char.float: Float get() = code.toFloat()
inline val Char.double: Double get() = code.toDouble()
inline val Char.char: Char get() = toChar()

inline val Float.long: Long get() = toLong()
inline val Float.asULong: Long get() = toULong()
inline val Float.int: Int get() = toInt()
inline val Float.short: Short get() = toInt().toShort()
inline val Float.byte: Byte get() = toInt().toByte()
inline val Float.float: Float get() = toFloat()
inline val Float.double: Double get() = toDouble()

inline val Double.long: Long get() = toLong()
inline val Double.asULong: Long get() = toULong()
inline val Double.int: Int get() = toInt()
inline val Double.short: Short get() = toInt().toShort()
inline val Double.byte: Byte get() = toInt().toByte()
inline val Double.float: Float get() = toFloat()
inline val Double.double: Double get() = toDouble()